name: CI
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        LOOP: [0, 1, 2]
        # https://docs.github.com/en/actions/reference/runners/github-hosted-runners
        os:
          - windows-2025      # x86_64
        qt_ver:
          - 6.1.0
          - 6.2.2
          - 6.11.0
        iqta_setup_py: ['true', 'false']
        aqt_commit: 
          - 'b22c86daef2ceeab6635ee0851e089f7346ec286'  # Jun  2, 2025, v3.3.0
          - '8c3695d4a4e1ceabf6a74dc6c79681656dc6b74b'  # Mar 24, 2026, PR #1000 fixes Qt 6.11 on Windows
          - '16db45a70b5905ad596941b223469bc86a56901e'  # Jul 22, 2026, latest master
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Python
        if: ${{ matrix.iqta_setup_py == 'false' }}
        uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.14'
      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.1
        with:
          version: ${{ matrix.qt_ver }}
          setup-python: ${{ matrix.iqta_setup_py }}
          aqtsource: "git+https://github.com/miurahr/aqtinstall.git@${{ matrix.aqt_commit }}"
